platform: linux 

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: CapstoneProject

  
outputs:
  - name: resource-app
  
#run:
 #path: sh
 #args: ["CapstoneProject/ci/build.sh"]
 #params:
 # MAVEN_BASEDIR: resource-app
 
run:
  path: mvn
  args: ["-f", "CapstoneProject/pom.xml", "-DskipTests=true", "package"]
