platform: linux 

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: CapstoneProject

  
outputs:
  - name: CapstoneProject
  
run:
 path: sh
 args: ["CapstoneProject/ci/build.sh"]
