platform: linux 

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: ppTest

  
outputs:
  - name: resource-app
  
run:
 path: chmod -R 777 ppTest/ci/build.sh; ./ppTest/ci/build.sh
 #args: ["ppTest/ci/build.sh"]